name: Draft new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The new version in major.minor.patch format.
        required: true

jobs:
  draft-new-release:
    name: Draft a new release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.version }}

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.3.0
        with:
          tag: ${{ format('v{0}', github.event.inputs.version) }}
          changelogPath: CHANGELOG.md

      - name: Bump version in Cargo.toml
        uses: thomaseizinger/set-crate-version@1.0.0
        with:
          version: ${{ github.event.inputs.version }}
          manifest: Cargo.toml

      - name: Format CHANGELOG
        run: |
          curl -fsSL https://dprint.dev/install.sh | sh
          /home/runner/.dprint/bin/dprint fmt CHANGELOG.md

      - name: Add & Commit
        id: make-commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: Prepare release ${{ github.event.inputs.version }}
          branch: release/${{ github.event.inputs.version }}
          default_author: github_actions
          pull: 'NO-PULL'
          push: false

      - name: Push new branch
        run: git push origin release/${{ github.event.inputs.version }} --force

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@1.2.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release/${{ github.event.inputs.version }}
          base: main
          title: Release version ${{ github.event.inputs.version }}
          body: |
            Hi @${{ github.actor }}!

            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            I've updated the changelog and bumped the versions in the manifest files in this commit: ${{ steps.make-commit.outputs.commit_sha }}.

            Merging this PR will create a GitHub release and may update the library/binary on crates.io!

